---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  vault-agent-config.hcl: |
    exit_after_auth = false
    pid_file = "/home/vault/pidfile"
    
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "kindergarten-role"
        }
      }
      
      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }
    
    template {
      destination = "/secrets/config.txt"
      contents = <<EOT
      {{- with secret "kindergarten/data/config" -}}
      MONGODB_URI={{ .Data.data.mongodb-uri }}
      DATABASE_NAME={{ .Data.data.database-name }}
      ELASTIC_APM_SERVER_URL={{ .Data.data.elastic-apm-server-url }}
      ELASTIC_APM_SECRET_TOKEN={{ .Data.data.elastic-apm-secret-token }}
      {{- end }}
      EOT
    }